version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    container_name: app
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app/app
    networks:
      - movies
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:1.21.5-alpine
    depends_on:
      - app
    ports:
      - 0.0.0.0:80:80
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - movies
    restart: unless-stopped

  db:
    image: postgres:13.0-alpine
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    networks:
      - movies
    restart: unless-stopped

networks:
  movies:
    external:
      name: movies