"""empty message

Revision ID: b53223a1eaac
Revises: cbff08dcdef1
Create Date: 2022-05-13 19:24:40.442102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b53223a1eaac'
down_revision = 'cbff08dcdef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    subs_status = postgresql.ENUM('ACTIVE', 'NEEDS_PAYMENT', 'EXPIRED', name='STATUS')
    subs_status.create(op.get_bind())
    op.add_column('subscriptions', sa.Column('status', subs_status, server_default='ACTIVE', nullable=False))
    op.add_column('subscriptions', sa.Column('grace_days', sa.Integer(), server_default='3', nullable=False))
    op.add_column('subscriptions', sa.Column('period', sa.Integer(), server_default='30', nullable=False))
    op.add_column('subscriptions', sa.Column('recurring', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'recurring')
    op.drop_column('subscriptions', 'period')
    op.drop_column('subscriptions', 'grace_days')
    op.drop_column('subscriptions', 'status')
    subs_status = postgresql.ENUM('ACTIVE', 'NEEDS_PAYMENT', 'EXPIRED', name='STATUS')
    subs_status.drop(op.get_bind())
    # ### end Alembic commands ###
