"""empty message

Revision ID: f0bbe26a01bc
Revises: af98bc30c073
Create Date: 2022-05-20 14:03:03.254791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0bbe26a01bc'
down_revision = 'fac8f648fd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index(op.f('ix_movies_name'), 'movies', ['name'], unique=True)
    op.drop_constraint('movies_name_key', 'movies', type_='unique')

    op.create_index('user_movies_movie_idx', 'user_movies', ['movie_id'], unique=False)
    op.create_index('user_movies_user_movie_unique_idx', 'user_movies', ['user_id', 'movie_id'], unique=True)

    op.create_index('user_subscription_status_expires_idx', 'user_subscriptions', ['status', 'expires'], unique=False)

    op.create_index(op.f('ix_users_stripe_cus_id'), 'users', ['stripe_cus_id'], unique=False)
    op.create_index(op.f('ix_users_user_subscription_id'), 'users', ['user_subscription_id'], unique=True)
    op.drop_constraint('users_user_subscription_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_user_subscription_id_key', 'users', ['user_subscription_id'])
    op.drop_index(op.f('ix_users_user_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_cus_id'), table_name='users')

    op.drop_index('user_subscription_status_expires_idx', table_name='user_subscriptions')

    op.drop_index('user_movies_user_movie_unique_idx', table_name='user_movies')
    op.drop_index('user_movies_movie_idx', table_name='user_movies')

    op.create_unique_constraint('movies_name_key', 'movies', ['name'])
    op.drop_index(op.f('ix_movies_name'), table_name='movies')
    # ### end Alembic commands ###
